###change {appname}, {dbname} and put sql files into ./database/postgresql#########

postgresql:
    image: postgres
    ports:
        - "54320:5432"
    container_name: postgresql-{appname}
    environment:
      - POSTGRES_DB={dbname}
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
        - /etc/localtime:/etc/localtime
        - ./database/postgresql:/docker-entrypoint-initdb.d
